### ISSUE TITLE
Put up development documentation in README

### ISSUE THREAD

**Issue by mbad0la** [kapilgarg1996/roadrunner#2]
It would be really beneficial for people if you could mention how can they set up the environment to test out your project locally, which will in turn help them learn from your code and spot some bugs.

**Comment by kapilgarg1996** [comment]
Thanks for pointing this out. Will release a full development documentation soon.

**Comment by kapilgarg1996** [comment]
@mbad0la documentation added. Now it would be great if you follow the steps and point out any fixes need to be done to setup roadrunner. Closing this issue

**Comment by mbad0la** [comment]
@kapilgarg1996 will do. And i'll get to learn Django through you :)
